name: Meu Workflow

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *' # Executa a cada hora

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      # Adicione suas ações pré-existentes aqui
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          
      # Adicione seus scripts personalizados aqui
      - name: Execute Script Personalizado
        run: |
          echo "Este é um script personalizado"
          npm install
          npm test
